name: Demo for Env and Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:  
  actions: read
  contents: read
  deployments: write

env:
  URL1: 'https://wwww.microsoft.com'
  URL: 'https://www.github.com'

jobs:
 use-environment-1:
   runs-on: ubuntu-latest
   if: ${{ github.event_name == 'pull_request' }}

   environment: 
     name: test
     url: ${{ env.URL1 }}

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Some step using the environment
       run: echo "In this step we could for example do the deployment to ${{ env.URL1 }} ..."


 use-environment-2:
   runs-on: ubuntu-latest
   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

   environment: 
     name: prod
     url: ${{ env.URL2 }}

   steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Some actions logic
        run: echo "In this step we could for example do the deployment to ${{ env.URL2 }}..."
      
      # Secrets are redacted in the logs
      - name: Echo a secret
        run: echo ${{ secrets.MY_REPO_SECRET }}
   
